# ????????? SQLite
spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.datasource.url=jdbc:sqlite:./schedule_db
spring.datasource.url=jdbc:sqlite:./data/schedule_db
# ????????? Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# ????????? ???????? ????? (SQLite ??????? ?????)
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=DEBUG
