#!/bin/bash
# Быстрый старт для работы с Shared Types

echo "🚀 Shared Types - Быстрый старт"
echo "================================"
echo ""
echo "📋 ШАГ 1: Запустите бэкенд"
echo "   cd backend && ./gradlew bootRun"
echo "   Подождите 10-15 секунд"
echo ""
echo "🌐 ШАГ 2: Откройте Swagger UI"
echo "   http://localhost:8080/swagger-ui.html"
echo ""
echo "📖 ШАГ 3: Пользуйтесь!"
echo "   • Раздел 'Schemas' показывает все ваши DTOs"
echo "   • Кнопка 'Try it out' позволяет попробовать API"
echo "   • Вmediately видите все поля и их типы"
echo ""
echo "💡 Как это помогает:"
echo "   Было: открываете Java файл → читаете код → пишете TypeScript"
echo "   Стало: открываете Swagger UI → копируете структуру → готово!"
echo ""
echo "📚 Документация:"
echo "   • Быстрый старт: docs/SWAGGER_QUICK_START.md"
echo "   • Полное руководство: docs/SHARED_TYPES_GUIDE.md"
echo ""
echo "🔧 Проверка типов:"
echo "   ./scripts/check-types-sync.sh"
echo ""
echo "✨ Начните прямо сейчас!"
