#!/bin/bash
# Quick reference for working with Shared Types

echo "🔧 Shared Types Quick Reference"
echo "================================"
echo ""
echo "📋 Check current types:"
echo "   ./scripts/check-types-sync.sh"
echo ""
echo "🚀 Start backend with Swagger UI:"
echo "   cd backend && ./gradlew bootRun"
echo "   Then open: http://localhost:8080/swagger-ui.html"
echo ""
echo "📖 How it works:"
echo "   1. Add field to Java DTO"
echo "   2. Restart backend"
echo "   3. Check field in Swagger UI"
echo "   4. Update TypeScript type"
echo ""
echo "💡 Example:"
echo "   Java:     String email added to EducatorDto"
echo "   Swagger:  Shows 'email' field in JSON"
echo "   TS:       Add 'email: string' to interface"
echo ""
echo "📚 Full guide: docs/SHARED_TYPES_GUIDE.md"
